server:
  port: 8081
spring:
  application:
    name: simulator
  mvc:
    servlet:
      path: /api
    throw-exception-if-no-handler-found: true # Para manejar errores 404
  web:
    resources:
       add-mappings: false # Desactiva el manejo automatico de recursos estaticos
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      telemetry: topic-telemetry
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      #Esto sirve para cuando se usa JsonSerializer, pero como usamos ByteArraySerializer, no es necesario
      #properties:
      #  spring.json.type.mapping: "sensor-dto:com.agonzalorena.msvc.simulator.presentation.dto.SensorDTO"
